language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - pip install virtualenv
  - sudo ln -s `which python3` /usr/local/bin/python3
  - sudo apt-get update
  - sudo apt-get install tesseract-ocr
install:
  - make venv
  - make install_requirements_dev
script: make tests